
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruueewpswsmmagpsxbvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1dWVld3Bzd3NtbWFncHN4YnZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNjA0MjIsImV4cCI6MjA2MTgzNjQyMn0.Q4b26dnooV_Kx1wywO6vuTJul8Z4ZTu5YnWhhK8FFUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: typeof window !== 'undefined' ? localStorage : undefined
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});
